ORIGINAL_DIRECTORY = '/Users/mrbinit/Desktop/untitled folder/datasets'
CHUNK_OUTPUT = '/Users/mrbinit/Desktop/untitled folder/output_chunk'
POSTGRES_USER='postgres'
POSTGRES_PASSWORD='admin123'
POSTGRES_HOST='localhost'
POSTGRES_PORT='5432'
POSTGRES_DB='binit'
TRANSCRIPTION_API_URL = 'https://your-transcription-api.com/transcribe'